### ISSUE TITLE
Rangt verð

### ISSUE THREAD

**Issue by olisisland** [gasvaktin/gasvaktin#11]
Hæ

Þessar 2 stöðvar eru ekki til, það eru ÓB stöðvar þarna með lægra verð. Hvar sækið þið þessar upplýsingar?
![image](https://user-images.githubusercontent.com/113615758/190429352-4a2441a2-9045-47a1-bea6-e222da0eed13.png)

**Comment by Loknar** [comment]
hæ og takk fyrir ábendinguna

> Hvar sækið þið þessar upplýsingar?

kóðann sem sækir Olís verð má sjá hér: https://github.com/gasvaktin/gasvaktin/blob/master/scripts/scraper.py#L225-L280

var að laga þetta, sjá https://github.com/gasvaktin/gasvaktin/commit/33d4b73755a8b401a9d6d1cf0a4887783a93e7c8

hér er "blame" á commit id fyrir lagfæringu https://github.com/gasvaktin/gasvaktin/blame/97d2ccd9715a451b487a428d3b4e014c90dfc4ec/scripts/scraper.py

í ofangreindu blame sést commit sem segir að fyrir þremur árum var verið að uppfæra Olís vefsíðuna og kom reglulega fyrir að verð vantaði í stöðvalistann, sjá https://github.com/gasvaktin/gasvaktin/commit/6d06a33d5f172b84115c36c412ad6fa43a45fbdc, þá bætti ég í Olís verðskröpuna að athuga hæsta bensín og dísil verð og setja það verð á stöðvar sem vantaði að birta verð fyrir, þessi highest price lógík var að setja hæsta verð á stöðvarnar Olís Stykkishólmur og Olís Vestmannaeyjar, en þær stöðvar voru enn til staðar í https://github.com/gasvaktin/gasvaktin/blob/master/stations/olis.json

biðst velvirðingar á þessu, og takk aftur fyrir að benda á þetta

mbk
