### ISSUE TITLE
Station 84 from N1 closed?

### ISSUE THREAD

**Issue by Fabi755** [gasvaktin/gasvaktin#14]
The station `n1_084` is listed in the [stations](https://github.com/gasvaktin/gasvaktin/tree/880b31313ca8e6015cefa3a66763326ecddb160f/stations/n1.json#L575), but not in the [gas list](https://github.com/gasvaktin/gasvaktin/tree/880b31313ca8e6015cefa3a66763326ecddb160f/vaktin/gas.json#L1406) anymore.

Is this station closed, any information about this?

**Comment by Loknar** [comment]
I'm afk atm, but I'll take a look in the evening.

**Comment by Fabi755** [comment]
Thank you! I think, it's not urgent :-)

**Comment by Loknar** [comment]
ah, yes I remember

this is an N1 self service pump stationed [here in Skútuvogur](https://maps.google.com/?z=14&q=%2864.138332,-21.848176%29)

for a time it was in open accessible area, it seems to have been set up for the company Vaka over there, that offers towing services, and strips and sells car parts and more

there came a time when they added a fence around the perimeter, so the station is more or less only accessible to the Vaka company now

I'll clean it up now, thanks for pointing this out
