### ISSUE TITLE
Will be adding CostCo?

### ISSUE THREAD

**Issue by kertavax** [gasvaktin/gasvaktin#2]
Not an “issue” per se – more of a question on if you might be [adding CostCo to the listings](http://www.visir.is/g/2017170529868/bensinstod-costc-opnud-selja-bensin-a-169-9-kronur)?

I’m not entirely sure where to gather their data from, or in what form they might be offering it. Perhaps [GSMbensín](http://gsmbensin.is/gsmbensin_web.php) might know?

**Comment by Loknar** [comment]
I've sent CostCo in Iceland an email few days ago asking if they were planning to show their petrol price on their website. I haven't received a reply from them yet.

Surely I could hardcode their prices like I did at first with Dælan ... but I'd rather not unless I have a contact I can ask for updated prices ...

**Comment by kertavax** [comment]
That makes total sense. Thanks for the quick reply, cheers!
